name: Commit check
on: [pull_request]

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Commits Check
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@v1.3.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Verify PR title with regex
      id: regex
      run: |
        echo "Commits: ${{ steps.get-pr-commits.outputs.commits }}"
        for variable in $(echo -e "${{ steps.get-pr-commits.outputs.commits }}"); do
          echo "commit"
          echo $variable
        done
