name: Git Checks

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main


jobs:
  block-fixup:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v3
      - name: Block Fixup Commit Merge
        uses: 13rac1/block-fixup-merge-action@v2.0.0

  verify-commit-title:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Verify commit title with regex
        id: regex
        run: |
            for commit in ${{ github.event.commits }}; do
              echo "${{ commit.message }}"
            title=$(cat <<'EOF'
            ${{ commit.message }}
            EOF
            )
            # Regular expression we'll use to analyze the string
            regex='^(docs|fix|feat|build|ci|chore|perf|refactor|revert|style|test)(\([_0-9a-zA-Z-]+\))?: .+$'
            # Perform regex check and determine if title is correct
            if [[ $title =~ $regex ]]
            then
                echo "Commit ${{ commit.message }} OK"
            else
                echo "Failing Check Test for commit ${{ commit.message }}"
                exit 1
            fi
