name: Commit check
on: [pull_request]

jobs:
  commit-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Commits
        uses: ./.github/commit-check.yml
        with:
          regexPattern: '^(docs|fix|feat|build|ci|chore|perf|refactor|revert|style|test)(\([_0-9a-zA-Z-]+\))?: .+$'
