name: Commit check
on: [pull_request]

jobs:
  commits_check_job:
    runs-on: ubuntu-latest
    name: Commits Check
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@v1.3.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Check Commits
      run: |
        echo "Commits: ${{ steps.get-pr-commits.outputs.commits }}"
