name: Commit check
on: [pull_request]

jobs:
  commit-check:
    runs-on: ubuntu-latest

    runs:
      using: 'docker'
      image: '../Dockerfile'
      args:
        - '^(docs|fix|feat|build|ci|chore|perf|refactor|revert|style|test)(\([_0-9a-zA-Z-]+\))?: .+$'
