name: Doc Checker

on:
  pull_request:
#  push:
#    branches:
#      - main

jobs:
  check_for_docs:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      # Warning: will clobber manual changes while in draft
      - name: Check out Repository
        uses: actions/checkout@v3
#        with:
#           fetch-depth: 2

      - uses: jitterbit/get-changed-files@v1
        id: changed
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Look for markdown files
        id: check_markdown
        if: startsWith( "${{ github.event.pull_request.title }}", "feat:" )
        run: |
          echo "${{ steps.changed.outputs.added_modified }}"
          echo ${{ steps.changed.outputs.added_modified }} | grep -E '\.md$'
          if [[ ${{ steps.changed.outputs.added_modified }} | grep -E '\.md$') ]]; then
            echo "docs_missing=true" >> $GITHUB_ENV
          fi

      - name: Add label if no documentation
        if: steps.check_markdown.outputs.docs_missing == 'true'
        run: |
          echo gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: ":rotating_light: **This PR is missing documentation**"
