name: Doc Checker

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      # Warning: will clobber manual changes while in draft
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
           fetch-depth: 2

      - uses: release-drafter/release-drafter@v5
        id: first_draft
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
      - name: Check if feat commit
        id: check_feat
        run: |
          if [[ "${{ github.event.pull_request.title }}" =~ "feat" ]]; then
            echo "is_feat=true" >> $GITHUB_ENV
          fi

      - name: Look for markdown files
        id: check_markdown
        if: steps.check_feat.outputs.is_feat == 'true'
        run: |
          if [[ $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.md$') ]]; then
            echo "docs_exist=true" >> $GITHUB_ENV
          fi
#            git diff --name-only -r HEAD^1 HEAD

      - name: Add label if no documentation
        if: steps.check_markdown.outputs.docs_exist != 'true'
        run: |
          echo gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: ":rotating_light: **This PR is missing documentation**"
