name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - uses: release-drafter/release-drafter@v5
        id: first_draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Look for setup.cfg
        id: check_setup_cfg
        uses: andstor/file-existence-action@v2
        with:
          files: "setup.cfg"

      - name: Define Setup File
        id: define_setup
        run: |
          if '${{ steps.check_setup_cfg.outputs.files_exists }}' == 'true'
          then
            echo "SETUP_FILE=setup.cfg" >> $GITHUB_OUTPUT
          else
            echo "SETUP_FILE=setup.py" >> $GITHUB_OUTPUT
          fi

      - name: Read Setup File
        id: read_setup
        uses: juliangruber/read-file-action@v1
        with:
          path: ${{ steps.define_setup.outputs.SETUP_FILE }}

      - name: Check for Tag Mismatch
        id: check_mismatch
        run: |
            UNCLEANED_DRAFTNAME="${{ steps.first_draft.outputs.name }}"
            DRAFTNAME=${UNCLEANED_DRAFTNAME//\./"\."}
            QUERY="version\s*\=\s*\"?${DRAFTNAME}\"?"
            if [[ '${{ steps.read_setup.outputs.content }}' =~ $QUERY ]]
            then
            else
              echo "VERSION_MATCH_MSG=:rotating_light: **The version in setup file ${{ steps.define_setup.outputs.SETUP_FILE }} still needs to be updated to ${{ steps.first_draft.outputs.name }} before publishing new release**" >> $GITHUB_OUTPUT
            fi

      - name: Re-draft
        if: steps.check_mismatch.outputs.VERSION_MATCH_MSG
        uses: release-drafter/release-drafter@v5
        with:
          header: ${{ steps.check_mismatch.outputs.VERSION_MATCH_MSG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
