name: Deploy Docker Images
run-name: Deploy Docker ${{ inputs.source }} Images to %{{ inputs.target }}

on:
  workflow_dispatch:
    inputs:
      source:
        description: "Source Tag (e.g. 1.0.9)"
        required: true
        type: string
      target:
        description: "Target Tag (e.g. rel)"
        required: true
        type: string

jobs:
  whatever:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: test
        run: echo "hello"
