name: Check Version Correct

on:
  release:
    types: [published]

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - name: Check out Repository
              uses: actions/checkout@v3

            - name: Check for setup.py
              id: check_files
              uses: andstor/file-existence-action@v2
              with:
                files: "setup.cfg"

            - name: Define Setup File
              id: define_setup
              run: |
                if '${{ steps.check_files.outputs.files_exists }}' == 'true'
                then
                  echo "SETUP_FILE=setup.cfg" >> $GITHUB_OUTPUT
                else
                  echo "SETUP_FILE=setup.py" >> $GITHUB_OUTPUT
                fi

            - name: Read Setup File
              id: read_setup
              uses: juliangruber/read-file-action@v1
              with:
                path: ${{ steps.define_setup.outputs.SETUP_FILE }}

            - name: Check for Tag Mismatch
              run: |
                  echo ${{ steps.define_setup.outputs.SETUP_FILE }}
                  echo "abc - ${{ steps.define_setup.outputs.SETUP_FILE }}"
                  echo "def - $GITHUB_REF"
                  echo "---"
                  if [[ '${{ steps.read_setup.outputs.content }}' =~ "version\s*=\s*\"?${{ env.GITHUB_REF }}\"?" ]]
                  then
                    echo "Setup version is correct!"
                  else
                    echo "Looks like there's a mismatch, have you updated the vesion in ${{ steps.define_setup.outputs.SETUP_FILE }} to ${{ env.GITHUB_REF }}?"
                    exit 1
                  fi
